remote_theme: tomjoht/documentation-theme-jekyll
# OR if you prefer using the gem
# theme: documentation-theme-jekyll

title: AdSDK Documentation
description: Documentation for the AdSDK video advertising platform
