title: AdSDK Documentation
description: Documentation for the AdSDK video advertising platform
theme: jekyll-theme-cayman

# Navigation structure (this preserves your existing document structure)
aux_links:
  "AdSDK on GitHub":
    - "https://github.com/NimiB2/Android-SDK-Ads"
