remote_theme: pmarsceill/just-the-docs

title: Video Ad SDK Documentation
description: Documentation for the AdSDK video advertising platform

# Navigation configuration
search_enabled: true
aux_links:
  "Ad Portal on GitHub":
    - "https://github.com/NimiB2/video-ad-portal"
  "Android SDK Documentation":
    - "https://nimib2.github.io/video-ad-sdk-android/"
  "Flask Backend Documentation":
    - "https://nimib2.github.io/video-ad-server/"

# Back to top link
back_to_top: true
back_to_top_text: "Back to top"
