# Theme
theme: jekyll-theme-cayman

# Site settings
title: AdSDK Documentation
description: Documentation for the Android AdSDK and API Server
show_downloads: false

# Navigation
nav:
  - title: Home
    url: /
  - title: Android SDK
    url: /android-sdk/getting-started
  - title: API Server
    url: /api-server/setup

# Plugins
plugins:
  - jekyll-relative-links

# Enable relative links
relative_links:
  enabled: true
  collections: true

# Default layout
defaults:
  - scope:
      path: ""
    values:
      layout: default
