title: AdSDK Documentation
description: Documentation for the AdSDK video advertising platform
remote_theme: pmarsceill/just-the-docs
color_scheme: light

# Enable search
search_enabled: true

# Aux links for the upper right navigation
aux_links:
  "AdSDK on GitHub":
    - "https://github.com/NimiB2/Android-SDK-Ads"

# Back to top link
back_to_top: true
back_to_top_text: "Back to top"
