remote_theme: pmarsceill/just-the-docs
# OR if you prefer using the gem
# theme: just-the-docs

title: AdSDK Documentation
description: Documentation for the AdSDK video advertising platform

# Navigation configuration
search_enabled: true
aux_links:
  "AdSDK on GitHub":
    - "https://github.com/NimiB2/Android-SDK-Ads"
